HRest -A -D -T 1 -S training/trainlist_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_arm_l -l arm_l -L data/train/lab/wordsleftarm/arm_l arm_l
HRest -A -D -T 1 -S training/trainlist_ba.txt -M model/hmm1 -H model/hmm0/hmm_ba -l ba -L data/train/lab/wordsfan/ba ba
HRest -A -D -T 1 -S training/trainlist_ba_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_ba_arm_l -l ba_arm_l -L data/train/lab/wordsleftarm/ba ba_arm_l
HRest -A -D -T 1 -S training/trainlist_ba_neck.txt -M model/hmm1 -H model/hmm0/hmm_ba_neck -l ba_neck -L data/train/lab/wordsneck/ba ba_neck
HRest -A -D -T 1 -S training/trainlist_changge.txt -M model/hmm1 -H model/hmm0/hmm_changge -l changge -L data/train/lab/wordsfan/changge changge
HRest -A -D -T 1 -S training/trainlist_changge_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_changge_arm_l -l changge_arm_l -L data/train/lab/wordsleftarm/changge changge_arm_l
HRest -A -D -T 1 -S training/trainlist_changge_neck.txt -M model/hmm1 -H model/hmm0/hmm_changge_neck -l changge_neck -L data/train/lab/wordsneck/changge changge_neck
HRest -A -D -T 1 -S training/trainlist_chayanguanse.txt -M model/hmm1 -H model/hmm0/hmm_chayanguanse -l chayanguanse -L data/train/lab/wordsfan/chayanguanse chayanguanse 
HRest -A -D -T 1 -S training/trainlist_chayanguanse_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_chayanguanse_arm_l -l chayanguanse_arm_l -L data/train/lab/wordsleftarm/chayanguanse chayanguanse_arm_l
HRest -A -D -T 1 -S training/trainlist_chayanguanse_neck.txt -M model/hmm1 -H model/hmm0/hmm_chayanguanse_neck -l chayanguanse_neck -L data/train/lab/wordsneck/chayanguanse chayanguanse_neck
HRest -A -D -T 1 -S training/trainlist_daiji.txt -M model/hmm1 -H model/hmm0/hmm_daiji -l daiji -L data/train/lab/wordsfan/daiji daiji
HRest -A -D -T 1 -S training/trainlist_daiji_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_daiji_arm_l -l daiji_arm_l -L data/train/lab/wordsleftarm/daiji daiji_arm_l
HRest -A -D -T 1 -S training/trainlist_daiji_neck.txt -M model/hmm1 -H model/hmm0/hmm_daiji_neck -l daiji_neck -L data/train/lab/wordsneck/daiji daiji_neck
HRest -A -D -T 1 -S training/trainlist_dataiji.txt -M model/hmm1 -H model/hmm0/hmm_dataiji -l dataiji -L data/train/lab/wordsfan/dataiji dataiji
HRest -A -D -T 1 -S training/trainlist_dataiji_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_dataiji_arm_l -l dataiji_arm_l -L data/train/lab/wordsleftarm/dataiji dataiji_arm_l
HRest -A -D -T 1 -S training/trainlist_dataiji_neck.txt -M model/hmm1 -H model/hmm0/hmm_dataiji_neck -l dataiji_neck -L data/train/lab/wordsneck/dataiji dataiji_neck
HRest -A -D -T 1 -S training/trainlist_dazhaohu.txt -M model/hmm1 -H model/hmm0/hmm_dazhaohu -l dazhaohu -L data/train/lab/wordsfan/dazhaohu dazhaohu
HRest -A -D -T 1 -S training/trainlist_dazhaohu_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_dazhaohu_arm_l -l dazhaohu_arm_l -L data/train/lab/wordsleftarm/dazhaohu dazhaohu_arm_l
HRest -A -D -T 1 -S training/trainlist_dazhaohu_neck.txt -M model/hmm1 -H model/hmm0/hmm_dazhaohu_neck -l dazhaohu_neck -L data/train/lab/wordsneck/dazhaohu dazhaohu_neck
HRest -A -D -T 1 -S training/trainlist_dingwei.txt -M model/hmm1 -H model/hmm0/hmm_dingwei -l dingwei -L data/train/lab/wordsfan/dingwei dingwei 
HRest -A -D -T 1 -S training/trainlist_dingwei_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_dingwei_arm_l -l dingwei_arm_l -L data/train/lab/wordsleftarm/dingwei dingwei_arm_l
HRest -A -D -T 1 -S training/trainlist_dingwei_neck.txt -M model/hmm1 -H model/hmm0/hmm_dingwei_neck -l dingwei_neck -L data/train/lab/wordsneck/dingwei dingwei_neck
HRest -A -D -T 1 -S training/trainlist_er.txt -M model/hmm1 -H model/hmm0/hmm_er -l er -L data/train/lab/wordsfan/er er 
HRest -A -D -T 1 -S training/trainlist_er_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_er_arm_l -l er_arm_l -L data/train/lab/wordsleftarm/er er_arm_l
HRest -A -D -T 1 -S training/trainlist_er_neck.txt -M model/hmm1 -H model/hmm0/hmm_er_neck -l er_neck -L data/train/lab/wordsneck/er er_neck
HRest -A -D -T 1 -S training/trainlist_ertingbafang.txt -M model/hmm1 -H model/hmm0/hmm_ertingbafang -l ertingbafang -L data/train/lab/wordsfan/ertingbafang ertingbafang
HRest -A -D -T 1 -S training/trainlist_ertingbafang_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_ertingbafang_arm_l -l ertingbafang_arm_l -L data/train/lab/wordsleftarm/ertingbafang ertingbafang_arm_l
HRest -A -D -T 1 -S training/trainlist_ertingbafang_neck.txt -M model/hmm1 -H model/hmm0/hmm_ertingbafang_neck -l ertingbafang_neck -L data/train/lab/wordsneck/ertingbafang ertingbafang_neck
HRest -A -D -T 1 -S training/trainlist_fan.txt -M model/hmm1 -H model/hmm0/hmm_fan -l fan -L data/train/lab/fan fan
HRest -A -D -T 1 -S training/trainlist_houtui.txt -M model/hmm1 -H model/hmm0/hmm_houtui -l houtui -L data/train/lab/wordsfan/houtui houtui
HRest -A -D -T 1 -S training/trainlist_houtui_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_houtui_arm_l -l houtui_arm_l -L data/train/lab/wordsleftarm/houtui houtui_arm_l
HRest -A -D -T 1 -S training/trainlist_houtui_neck.txt -M model/hmm1 -H model/hmm0/hmm_houtui_neck -l houtui_neck -L data/train/lab/wordsneck/houtui houtui_neck
HRest -A -D -T 1 -S training/trainlist_houzhuan.txt -M model/hmm1 -H model/hmm0/hmm_houzhuan -l houzhuan -L data/train/lab/wordsfan/houzhuan houzhuan
HRest -A -D -T 1 -S training/trainlist_houzhuan_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_houzhuan_arm_l -l houzhuan_arm_l -L data/train/lab/wordsleftarm/houzhuan houzhuan_arm_l
HRest -A -D -T 1 -S training/trainlist_houzhuan_neck.txt -M model/hmm1 -H model/hmm0/hmm_houzhuan_neck -l houzhuan_neck -L data/train/lab/wordsneck/houzhuan houzhuan_neck
HRest -A -D -T 1 -S training/trainlist_huishou.txt -M model/hmm1 -H model/hmm0/hmm_huishou -l huishou -L data/train/lab/wordsfan/huishou huishou
HRest -A -D -T 1 -S training/trainlist_huishou_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_huishou_arm_l -l huishou_arm_l -L data/train/lab/wordsleftarm/huishou huishou_arm_l
HRest -A -D -T 1 -S training/trainlist_huishou_neck.txt -M model/hmm1 -H model/hmm0/hmm_huishou_neck -l huishou_neck -L data/train/lab/wordsneck/huishou huishou_neck
HRest -A -D -T 1 -S training/trainlist_jirenlian.txt -M model/hmm1 -H model/hmm0/hmm_jirenlian -l jirenlian -L data/train/lab/wordsfan/jirenlian jirenlian
HRest -A -D -T 1 -S training/trainlist_jirenlian_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_jirenlian_arm_l -l jirenlian_arm_l -L data/train/lab/wordsleftarm/jirenlian jirenlian_arm_l
HRest -A -D -T 1 -S training/trainlist_jirenlian_neck.txt -M model/hmm1 -H model/hmm0/hmm_jirenlian_neck -l jirenlian_neck -L data/train/lab/wordsneck/jirenlian jirenlian_neck
HRest -A -D -T 1 -S training/trainlist_jiu.txt -M model/hmm1 -H model/hmm0/hmm_jiu -l jiu -L data/train/lab/wordsfan/jiu jiu
HRest -A -D -T 1 -S training/trainlist_jiu_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_jiu_arm_l -l jiu_arm_l -L data/train/lab/wordsleftarm/jiu jiu_arm_l
HRest -A -D -T 1 -S training/trainlist_jiu_neck.txt -M model/hmm1 -H model/hmm0/hmm_jiu_neck -l jiu_neck -L data/train/lab/wordsneck/jiu jiu_neck
HRest -A -D -T 1 -S training/trainlist_kan.txt -M model/hmm1 -H model/hmm0/hmm_kan -l kan -L data/train/lab/wordsfan/kan kan
HRest -A -D -T 1 -S training/trainlist_kan_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_kan_arm_l -l kan_arm_l -L data/train/lab/wordsleftarm/kan kan_arm_l
HRest -A -D -T 1 -S training/trainlist_kan_neck.txt -M model/hmm1 -H model/hmm0/hmm_kan_neck -l kan_neck -L data/train/lab/wordsneck/kan kan_neck
HRest -A -D -T 1 -S training/trainlist_liu.txt -M model/hmm1 -H model/hmm0/hmm_liu -l liu -L data/train/lab/wordsfan/liu liu
HRest -A -D -T 1 -S training/trainlist_liu_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_liu_arm_l -l liu_arm_l -L data/train/lab/wordsleftarm/liu liu_arm_l
HRest -A -D -T 1 -S training/trainlist_liu_neck.txt -M model/hmm1 -H model/hmm0/hmm_liu_neck -l liu_neck -L data/train/lab/wordsneck/liu liu_neck
HRest -A -D -T 1 -S training/trainlist_neck.txt -M model/hmm1 -H model/hmm0/hmm_neck -l neck -L data/train/lab/wordsneck/neck neck
HRest -A -D -T 1 -S training/trainlist_qi.txt -M model/hmm1 -H model/hmm0/hmm_qi -l qi -L data/train/lab/wordsfan/qi qi
HRest -A -D -T 1 -S training/trainlist_qi_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_qi_arm_l -l qi_arm_l -L data/train/lab/wordsleftarm/qi qi_arm_l
HRest -A -D -T 1 -S training/trainlist_qi_neck.txt -M model/hmm1 -H model/hmm0/hmm_qi_neck -l qi_neck -L data/train/lab/wordsneck/qi qi_neck
HRest -A -D -T 1 -S training/trainlist_qianjin.txt -M model/hmm1 -H model/hmm0/hmm_qianjin -l qianjin -L data/train/lab/wordsfan/qianjin qianjin
HRest -A -D -T 1 -S training/trainlist_qianjin_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_qianjin_arm_l -l qianjin_arm_l -L data/train/lab/wordsleftarm/qianjin qianjin_arm_l
HRest -A -D -T 1 -S training/trainlist_qianjin_neck.txt -M model/hmm1 -H model/hmm0/hmm_qianjin_neck -l qianjin_neck -L data/train/lab/wordsneck/qianjin qianjin_neck
HRest -A -D -T 1 -S training/trainlist_qili.txt -M model/hmm1 -H model/hmm0/hmm_qili -l qili -L data/train/lab/wordsfan/qili qili
HRest -A -D -T 1 -S training/trainlist_qili_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_qili_arm_l -l qili_arm_l -L data/train/lab/wordsleftarm/qili qili_arm_l
HRest -A -D -T 1 -S training/trainlist_qili_neck.txt -M model/hmm1 -H model/hmm0/hmm_qili_neck -l qili_neck -L data/train/lab/wordsneck/qili qili_neck
HRest -A -D -T 1 -S training/trainlist_san.txt -M model/hmm1 -H model/hmm0/hmm_san -l san -L data/train/lab/wordsfan/san san
HRest -A -D -T 1 -S training/trainlist_san_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_san_arm_l -l san_arm_l -L data/train/lab/wordsleftarm/san san_arm_l
HRest -A -D -T 1 -S training/trainlist_san_neck.txt -M model/hmm1 -H model/hmm0/hmm_san_neck -l san_neck -L data/train/lab/wordsneck/san san_neck
HRest -A -D -T 1 -S training/trainlist_shanqiyingren.txt -M model/hmm1 -H model/hmm0/hmm_shanqiyingren -l shanqiyingren -L data/train/lab/wordsfan/shanqiyingren shanqiyingren
HRest -A -D -T 1 -S training/trainlist_shanqiyingren_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_shanqiyingren_arm_l -l shanqiyingren_arm_l -L data/train/lab/wordsleftarm/shanqiyingren shanqiyingren_arm_l
HRest -A -D -T 1 -S training/trainlist_shanqiyingren_neck.txt -M model/hmm1 -H model/hmm0/hmm_shanqiyingren_neck -l shanqiyingren_neck -L data/train/lab/wordsneck/shanqiyingren shanqiyingren_neck
HRest -A -D -T 1 -S training/trainlist_shi.txt -M model/hmm1 -H model/hmm0/hmm_shi -l shi -L data/train/lab/wordsfan/shi shi
HRest -A -D -T 1 -S training/trainlist_shi_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_shi_arm_l -l shi_arm_l -L data/train/lab/wordsleftarm/shi shi_arm_l
HRest -A -D -T 1 -S training/trainlist_shi_neck.txt -M model/hmm1 -H model/hmm0/hmm_shi_neck -l shi_neck -L data/train/lab/wordsneck/shi shi_neck 
HRest -A -D -T 1 -S training/trainlist_shibie.txt -M model/hmm1 -H model/hmm0/hmm_shibie -l shibie -L data/train/lab/wordsfan/shibie shibie
HRest -A -D -T 1 -S training/trainlist_shibie_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_shibie_arm_l -l shibie_arm_l -L data/train/lab/wordsleftarm/shibie shibie_arm_l
HRest -A -D -T 1 -S training/trainlist_shibie_neck.txt -M model/hmm1 -H model/hmm0/hmm_shibie_neck -l shibie_neck -L data/train/lab/wordsneck/shibie shibie_neck
HRest -A -D -T 1 -S training/trainlist_shouzhudaitu.txt -M model/hmm1 -H model/hmm0/hmm_shouzhudaitu -l shouzhudaitu -L data/train/lab/wordsfan/shouzhudaitu shouzhudaitu
HRest -A -D -T 1 -S training/trainlist_shouzhudaitu_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_shouzhudaitu_arm_l -l shouzhudaitu_arm_l -L data/train/lab/wordsleftarm/shouzhudaitu shouzhudaitu_arm_l
HRest -A -D -T 1 -S training/trainlist_shouzhudaitu_neck.txt -M model/hmm1 -H model/hmm0/hmm_shouzhudaitu_neck -l shouzhudaitu_neck -L data/train/lab/wordsneck/shouzhudaitu shouzhudaitu_neck
HRest -A -D -T 1 -S training/trainlist_shuohua.txt -M model/hmm1 -H model/hmm0/hmm_shuohua -l shuohua -L data/train/lab/wordsfan/shuohua shuohua
HRest -A -D -T 1 -S training/trainlist_shuohua_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_shuohua_arm_l -l shuohua_arm_l -L data/train/lab/wordsleftarm/shuohua shuohua_arm_l
HRest -A -D -T 1 -S training/trainlist_shuohua_neck.txt -M model/hmm1 -H model/hmm0/hmm_shuohua_neck -l shuohua_neck -L data/train/lab/wordsneck/shuohua shuohua_neck
HRest -A -D -T 1 -S training/trainlist_si.txt -M model/hmm1 -H model/hmm0/hmm_si -l si -L data/train/lab/wordsfan/si si
HRest -A -D -T 1 -S training/trainlist_si_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_si_arm_l -l si_arm_l -L data/train/lab/wordsleftarm/si si_arm_l
HRest -A -D -T 1 -S training/trainlist_si_neck.txt -M model/hmm1 -H model/hmm0/hmm_si_neck -l si_neck -L data/train/lab/wordsneck/si si_neck
HRest -A -D -T 1 -S training/trainlist_taitou.txt -M model/hmm1 -H model/hmm0/hmm_taitou -l taitou -L data/train/lab/wordsfan/taitou taitou
HRest -A -D -T 1 -S training/trainlist_taitou_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_taitou_arm_l -l taitou_arm_l -L data/train/lab/wordsleftarm/taitou taitou_arm_l
HRest -A -D -T 1 -S training/trainlist_taitou_neck.txt -M model/hmm1 -H model/hmm0/hmm_taitou_neck -l taitou_neck -L data/train/lab/wordsneck/taitou taitou_neck
HRest -A -D -T 1 -S training/trainlist_taotaobujue.txt -M model/hmm1 -H model/hmm0/hmm_taotaobujue -l taotaobujue -L data/train/lab/wordsfan/taotaobujue taotaobujue
HRest -A -D -T 1 -S training/trainlist_taotaobujue_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_taotaobujue_arm_l -l taotaobujue_arm_l -L data/train/lab/wordsleftarm/taotaobujue taotaobujue_arm_l
HRest -A -D -T 1 -S training/trainlist_taotaobujue_neck.txt -M model/hmm1 -H model/hmm0/hmm_taotaobujue_neck -l taotaobujue_neck -L data/train/lab/wordsneck/taotaobujue taotaobujue_neck
HRest -A -D -T 1 -S training/trainlist_tiaowu.txt -M model/hmm1 -H model/hmm0/hmm_tiaowu -l tiaowu -L data/train/lab/wordsfan/tiaowu tiaowu
HRest -A -D -T 1 -S training/trainlist_tiaowu_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_tiaowu_arm_l -l tiaowu_arm_l -L data/train/lab/wordsleftarm/tiaowu tiaowu_arm_l
HRest -A -D -T 1 -S training/trainlist_tiaowu_neck.txt -M model/hmm1 -H model/hmm0/hmm_tiaowu_neck -l tiaowu_neck -L data/train/lab/wordsneck/tiaowu tiaowu_neck
HRest -A -D -T 1 -S training/trainlist_ting.txt -M model/hmm1 -H model/hmm0/hmm_ting -l ting -L data/train/lab/wordsfan/ting ting
HRest -A -D -T 1 -S training/trainlist_ting1.txt -M model/hmm1 -H model/hmm0/hmm_ting1 -l ting1 -L data/train/lab/wordsfan/ting1 ting1
HRest -A -D -T 1 -S training/trainlist_ting1_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_ting1_arm_l -l ting1_arm_l -L data/train/lab/wordsleftarm/ting1 ting1_arm_l
HRest -A -D -T 1 -S training/trainlist_ting1_neck.txt -M model/hmm1 -H model/hmm0/hmm_ting1_neck -l ting1_neck -L data/train/lab/wordsneck/ting1 ting1_neck
HRest -A -D -T 1 -S training/trainlist_ting_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_ting_arm_l -l ting_arm_l -L data/train/lab/wordsleftarm/ting ting_arm_l
HRest -A -D -T 1 -S training/trainlist_ting_neck.txt -M model/hmm1 -H model/hmm0/hmm_ting_neck -l ting_neck -L data/train/lab/wordsneck/ting ting_neck
HRest -A -D -T 1 -S training/trainlist_tingzhi.txt -M model/hmm1 -H model/hmm0/hmm_tingzhi -l tingzhi -L data/train/lab/wordsfan/tingzhi tingzhi
HRest -A -D -T 1 -S training/trainlist_tingzhi_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_tingzhi_arm_l -l tingzhi_arm_l -L data/train/lab/wordsleftarm/tingzhi tingzhi_arm_l
HRest -A -D -T 1 -S training/trainlist_tingzhi_neck.txt -M model/hmm1 -H model/hmm0/hmm_tingzhi_neck -l tingzhi_neck -L data/train/lab/wordsneck/tingzhi tingzhi_neck
HRest -A -D -T 1 -S training/trainlist_wangqianzou.txt -M model/hmm1 -H model/hmm0/hmm_wangqianzou -l wangqianzou -L data/train/lab/wordsfan/wangqianzou wangqianzou
HRest -A -D -T 1 -S training/trainlist_wangqianzou_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_wangqianzou_arm_l -l wangqianzou_arm_l -L data/train/lab/wordsleftarm/wangqianzou wangqianzou_arm_l
HRest -A -D -T 1 -S training/trainlist_wangqianzou_neck.txt -M model/hmm1 -H model/hmm0/hmm_wangqianzou_neck -l wangqianzou_neck -L data/train/lab/wordsneck/wangqianzou wangqianzou_neck
HRest -A -D -T 1 -S training/trainlist_wenjiqiwu.txt -M model/hmm1 -H model/hmm0/hmm_wenjiqiwu -l wenjiqiwu -L data/train/lab/wordsfan/wenjiqiwu wenjiqiwu
HRest -A -D -T 1 -S training/trainlist_wenjiqiwu_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_wenjiqiwu_arm_l -l wenjiqiwu_arm_l -L data/train/lab/wordsleftarm/wenjiqiwu wenjiqiwu_arm_l
HRest -A -D -T 1 -S training/trainlist_wenjiqiwu_neck.txt -M model/hmm1 -H model/hmm0/hmm_wenjiqiwu_neck -l wenjiqiwu_neck -L data/train/lab/wordsneck/wenjiqiwu wenjiqiwu_neck
HRest -A -D -T 1 -S training/trainlist_wu.txt -M model/hmm1 -H model/hmm0/hmm_wu -l wu -L data/train/lab/wordsfan/wu wu
HRest -A -D -T 1 -S training/trainlist_wu_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_wu_arm_l -l wu_arm_l -L data/train/lab/wordsleftarm/wu wu_arm_l
HRest -A -D -T 1 -S training/trainlist_wu_neck.txt -M model/hmm1 -H model/hmm0/hmm_wu_neck -l wu_neck -L data/train/lab/wordsneck/wu wu_neck
HRest -A -D -T 1 -S training/trainlist_xiadun.txt -M model/hmm1 -H model/hmm0/hmm_xiadun -l xiadun -L data/train/lab/wordsfan/xiadun xiadun
HRest -A -D -T 1 -S training/trainlist_xiadun_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_xiadun_arm_l -l xiadun_arm_l -L data/train/lab/wordsleftarm/xiadun xiadun_arm_l
HRest -A -D -T 1 -S training/trainlist_xiadun_neck.txt -M model/hmm1 -H model/hmm0/hmm_xiadun_neck -l xiadun_neck -L data/train/lab/wordsneck/xiadun xiadun_neck
HRest -A -D -T 1 -S training/trainlist_xianghoutui.txt -M model/hmm1 -H model/hmm0/hmm_xianghoutui -l xianghoutui -L data/train/lab/wordsfan/xianghoutui xianghoutui
HRest -A -D -T 1 -S training/trainlist_xianghoutui_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_xianghoutui_arm_l -l xianghoutui_arm_l -L data/train/lab/wordsleftarm/xianghoutui xianghoutui_arm_l
HRest -A -D -T 1 -S training/trainlist_xianghoutui_neck.txt -M model/hmm1 -H model/hmm0/hmm_xianghoutui_neck -l xianghoutui_neck -L data/train/lab/wordsneck/xianghoutui xianghoutui_neck
HRest -A -D -T 1 -S training/trainlist_xiangyouzhuan.txt -M model/hmm1 -H model/hmm0/hmm_xiangyouzhuan -l xiangyouzhuan -L data/train/lab/wordsfan/xiangyouzhuan xiangyouzhuan
HRest -A -D -T 1 -S training/trainlist_xiangyouzhuan_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_xiangyouzhuan_arm_l -l xiangyouzhuan_arm_l -L data/train/lab/wordsleftarm/xiangyouzhuan xiangyouzhuan_arm_l
HRest -A -D -T 1 -S training/trainlist_xiangyouzhuan_neck.txt -M model/hmm1 -H model/hmm0/hmm_xiangyouzhuan_neck -l xiangyouzhuan_neck -L data/train/lab/wordsneck/xiangyouzhuan xiangyouzhuan_neck
HRest -A -D -T 1 -S training/trainlist_xiangzuozhuan.txt -M model/hmm1 -H model/hmm0/hmm_xiangzuozhuan -l xiangzuozhuan -L data/train/lab/wordsfan/xiangzuozhuan xiangzuozhuan
HRest -A -D -T 1 -S training/trainlist_xiangzuozhuan_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_xiangzuozhuan_arm_l -l xiangzuozhuan_arm_l -L data/train/lab/wordsleftarm/xiangzuozhuan xiangzuozhuan_arm_l
HRest -A -D -T 1 -S training/trainlist_xiangzuozhuan_neck.txt -M model/hmm1 -H model/hmm0/hmm_xiangzuozhuan_neck -l xiangzuozhuan_neck -L data/train/lab/wordsneck/xiangzuozhuan xiangzuozhuan_neck
HRest -A -D -T 1 -S training/trainlist_xingzou.txt -M model/hmm1 -H model/hmm0/hmm_xingzou -l xingzou -L data/train/lab/wordsfan/xingzou xingzou
HRest -A -D -T 1 -S training/trainlist_xingzou_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_xingzou_arm_l -l xingzou_arm_l -L data/train/lab/wordsleftarm/xingzou xingzou_arm_l
HRest -A -D -T 1 -S training/trainlist_xingzou_neck.txt -M model/hmm1 -H model/hmm0/hmm_xingzou_neck -l xingzou_neck -L data/train/lab/wordsneck/xingzou xingzou_neck
HRest -A -D -T 1 -S training/trainlist_yi.txt -M model/hmm1 -H model/hmm0/hmm_yi -l yi -L data/train/lab/wordsfan/yi yi
HRest -A -D -T 1 -S training/trainlist_yi_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_yi_arm_l -l yi_arm_l -L data/train/lab/wordsleftarm/yi yi_arm_l 
HRest -A -D -T 1 -S training/trainlist_yi_neck.txt -M model/hmm1 -H model/hmm0/hmm_yi_neck -l yi_neck -L data/train/lab/wordsneck/yi yi_neck
HRest -A -D -T 1 -S training/trainlist_yiyanbufa.txt -M model/hmm1 -H model/hmm0/hmm_yiyanbufa -l yiyanbufa -L data/train/lab/wordsfan/yiyanbufa yiyanbufa
HRest -A -D -T 1 -S training/trainlist_yiyanbufa_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_yiyanbufa_arm_l -l yiyanbufa_arm_l -L data/train/lab/wordsleftarm/yiyanbufa yiyanbufa_arm_l
HRest -A -D -T 1 -S training/trainlist_yiyanbufa_neck.txt -M model/hmm1 -H model/hmm0/hmm_yiyanbufa_neck -l yiyanbufa_neck -L data/train/lab/wordsneck/yiyanbufa yiyanbufa_neck
HRest -A -D -T 1 -S training/trainlist_youzhuan.txt -M model/hmm1 -H model/hmm0/hmm_youzhuan -l youzhuan -L data/train/lab/wordsfan/youzhuan youzhuan
HRest -A -D -T 1 -S training/trainlist_youzhuan_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_youzhuan_arm_l -l youzhuan_arm_l -L data/train/lab/wordsleftarm/youzhuan youzhuan_arm_l
HRest -A -D -T 1 -S training/trainlist_youzhuan_neck.txt -M model/hmm1 -H model/hmm0/hmm_youzhuan_neck -l youzhuan_neck -L data/train/lab/wordsneck/youzhuan youzhuan_neck
HRest -A -D -T 1 -S training/trainlist_zhan.txt -M model/hmm1 -H model/hmm0/hmm_zhan -l zhan -L data/train/lab/wordsfan/zhan zhan
HRest -A -D -T 1 -S training/trainlist_zhan_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_zhan_arm_l -l zhan_arm_l -L data/train/lab/wordsleftarm/zhan zhan_arm_l
HRest -A -D -T 1 -S training/trainlist_zhan_neck.txt -M model/hmm1 -H model/hmm0/hmm_zhan_neck -l zhan_neck -L data/train/lab/wordsneck/zhan zhan_neck
HRest -A -D -T 1 -S training/trainlist_zhaoshengyin.txt -M model/hmm1 -H model/hmm0/hmm_zhaoshengyin -l zhaoshengyin -L data/train/lab/wordsfan/zhaoshengyin zhaoshengyin
HRest -A -D -T 1 -S training/trainlist_zhaoshengyin_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_zhaoshengyin_arm_l -l zhaoshengyin_arm_l -L data/train/lab/wordsleftarm/zhaoshengyin zhaoshengyin_arm_l
HRest -A -D -T 1 -S training/trainlist_zhaoshengyin_neck.txt -M model/hmm1 -H model/hmm0/hmm_zhaoshengyin_neck -l zhaoshengyin_neck -L data/train/lab/wordsneck/zhaoshengyin zhaoshengyin_neck
HRest -A -D -T 1 -S training/trainlist_zhuantou.txt -M model/hmm1 -H model/hmm0/hmm_zhuantou -l zhuantou -L data/train/lab/wordsfan/zhuantou zhuantou
HRest -A -D -T 1 -S training/trainlist_zhuantou_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_zhuantou_arm_l -l zhuantou_arm_l -L data/train/lab/wordsleftarm/zhuantou zhuantou_arm_l
HRest -A -D -T 1 -S training/trainlist_zhuantou_neck.txt -M model/hmm1 -H model/hmm0/hmm_zhuantou_neck -l zhuantou_neck -L data/train/lab/wordsneck/zhuantou zhuantou_neck
HRest -A -D -T 1 -S training/trainlist_zou.txt -M model/hmm1 -H model/hmm0/hmm_zou -l zou -L data/train/lab/wordsfan/zou zou
HRest -A -D -T 1 -S training/trainlist_zou_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_zou_arm_l -l zou_arm_l -L data/train/lab/wordsleftarm/zou zou_arm_l
HRest -A -D -T 1 -S training/trainlist_zou_neck.txt -M model/hmm1 -H model/hmm0/hmm_zou_neck -l zou_neck -L data/train/lab/wordsneck/zou zou_neck
HRest -A -D -T 1 -S training/trainlist_zuo.txt -M model/hmm1 -H model/hmm0/hmm_zuo -l zuo -L data/train/lab/wordsfan/zuo zuo
HRest -A -D -T 1 -S training/trainlist_zuo_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_zuo_arm_l -l zuo_arm_l -L data/train/lab/wordsleftarm/zuo zuo_arm_l
HRest -A -D -T 1 -S training/trainlist_zuo_neck.txt -M model/hmm1 -H model/hmm0/hmm_zuo_neck -l zuo_neck -L data/train/lab/wordsneck/zuo zuo_neck
HRest -A -D -T 1 -S training/trainlist_zuoguyoupan.txt -M model/hmm1 -H model/hmm0/hmm_zuoguyoupan -l zuoguyoupan -L data/train/lab/wordsfan/zuoguyoupan zuoguyoupan
HRest -A -D -T 1 -S training/trainlist_zuoguyoupan_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_zuoguyoupan_arm_l -l zuoguyoupan_arm_l -L data/train/lab/wordsleftarm/zuoguyoupan zuoguyoupan_arm_l
HRest -A -D -T 1 -S training/trainlist_zuoguyoupan_neck.txt -M model/hmm1 -H model/hmm0/hmm_zuoguyoupan_neck -l zuoguyoupan_neck -L data/train/lab/wordsneck/zuoguyoupan zuoguyoupan_neck
HRest -A -D -T 1 -S training/trainlist_zuozhuan.txt -M model/hmm1 -H model/hmm0/hmm_zuozhuan -l zuozhuan -L data/train/lab/wordsfan/zuozhuan zuozhuan
HRest -A -D -T 1 -S training/trainlist_zuozhuan_arm_l.txt -M model/hmm1 -H model/hmm0/hmm_zuozhuan_arm_l -l zuozhuan_arm_l -L data/train/lab/wordsleftarm/zuozhuan zuozhuan_arm_l
HRest -A -D -T 1 -S training/trainlist_zuozhuan_neck.txt -M model/hmm1 -H model/hmm0/hmm_zuozhuan_neck -l zuozhuan_neck -L data/train/lab/wordsneck/zuozhuan zuozhuan_neck